---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load Packages
library(sf)                   # Load the 'sf' package for handling spatial data
library(tidyverse)            # Load the 'tidyverse' package for data manipulation
library(here)                 # Load the 'here' package for constructing reliable file paths
library(raster)               # Load the 'raster' package for handling raster data
library(exactextractr)        # Load the 'exactextractr' package for extracting raster data
library(ggspatial)
library(terra)
library(tmap)
```

```{r}
# Load the Merged Data (spatial)
## The data has been created under the 'hands_on_exercise2' script

state_med_colleges_sf <- readr::read_rds(here("spatial_files", "state_med_colleges_sf.rds"))
```

```{r}
summary(state_med_colleges_sf)
```
```{r}
head(state_med_colleges_sf)
```


```{r}
plot(state_med_colleges_sf)
```
```{r}
india <- state_med_colleges_sf$geometry |> st_make_valid() |> st_union()

# shape is still invalid, state boundaries overlap and distort the final union
```

```{r}
# tmap_mode("view")
# tmap_options(check.and.fix = TRUE)
# 
# tm_shape(india) + tm_polygons(alpha = 0.5)
```


```{r}
# Create a new attribute for the dataset called state_population
# The population counts are coming from the SEDAC Raster <https://sedac.ciesin.columbia.edu/>
# The raster file is stored in the 'spatial_files' folder 
# (gpw_v4_population_count_rev11_2020_5_min.tif)
# Lets Load it

pop_raster <- raster(here("spatial_files", "gpw_v4_population_count_rev11_2020_5_min.tif"))
```

```{r}
summary(pop_raster)
```
```{r}
head(pop_raster)
```

```{r}
# Plot the raster
pop_raster |> 
  plot()
```

```{r}
# Reproject the spatial object to match the raster's CRS
state_med_colleges_sf <- st_transform(state_med_colleges_sf, crs(pop_raster))
```


```{r}
# Crop the raster to the extent of the state_med_colleges_sf data set
ind_pop_raster <- crop(pop_raster, state_med_colleges_sf)
```

```{r}
# Plot Cropped Raster
ind_pop_raster |> 
  plot()
```
```{r}
# Extract Population Counts for each of the State
exactextractr::exact_extract(ind_pop_raster, 
                             state_med_colleges_sf, 
                             fun = "sum")

state_med_colleges_sf  <- state_med_colleges_sf |> 
  mutate(state_pop_2020 = exactextractr::exact_extract(ind_pop_raster, 
                                                       state_med_colleges_sf, 
                                                       fun = "sum"))
state_med_colleges_sf |> 
  write_rds(here("spatial_files", "state_med_colleges_sf.rds"))

state_med_colleges_sf |> 
  st_drop_geometry() |>
  summarise(tot_pop = sum(state_pop_2020))
```
```{r}
# Create number of medical colleges per 1 million population
state_med_colleges_sf <- state_med_colleges_sf |> 
  mutate(med_coll_per_million = no_of_colleges / (state_pop_2020 / 1e6))
```

```{r}
# Create a Choropleth of Medical Colleges per Million Population
# Plot a Choropleth
state_med_colleges_sf |> 
  ggplot() +
  geom_sf(aes(fill = med_coll_per_million))

```

```{r}
# Change Color Palette
state_med_colleges_sf |> 
  ggplot() +
  geom_sf(aes(fill = med_coll_per_million)) +
  scale_fill_viridis_c(trans = "log") # Log Transformation
```

```{r}
# Add Additional Map Elements
state_med_colleges_sf |> 
  ggplot() +
  geom_sf(aes(fill = med_coll_per_million)) +
  scale_fill_viridis_c(trans = "log") + 
  annotation_scale(location = "bl") + # Add Scale
  annotation_north_arrow(location = "tr", which_north = "true") + # add north arrow
  labs(title = "Medical Colleges per Million Population in India",
       subtitle = "Medical College Data from the National Medical Council (NMC) \nPopulation Data from SEDAC, NASA",
       caption = "Note: The states of Lakshwadeep and Ladakh do not have any medical colleges (Grey)",
       fill = "Medical Colleges per Million Population") +
  theme_minimal()
```
```{r}
# Save the plot
ggsave(file = here("plots", "med_college_pm_choropleth_map.png"),
       width = 6, 
       height = 6,
       scale = 1.2)

# Save the Data as an RDS file
state_med_colleges_sf |> 
  write_rds(here("spatial_files", "state_med_colleges_sf.rds"))
```

